baseURL = "/"
languageCode = "en"
title = "Evagene"
paginate = 5
[markup]
	defaultMarkdownHandler = "goldmark"
	[markup.tableOfContents]
		endLevel = 3
		startLevel = 2
		ordered = true
  [markup.goldmark]
		[markup.goldmark.extensions]
			typographer = false
    [markup.goldmark.renderer]
      unsafe = true
